### ISSUE TITLE
Issue with checkTags

### ISSUE THREAD

**Issue by Kiranpanjam** [mikela/SomeDataprocSparkJob#1]
Were you able to figure this out?

**Comment by mikela** [comment]
Yes, put the Dataproc clusters and Cloud SQL in a VPC network and just use the [private IP](https://cloud.google.com/sql/docs/mysql/private-ip). No need to use the Cloud SQL Proxy.

**Comment by Kiranpanjam** [comment]
But I do not have any Cloud SQL. My spark session builder is as below:
      
      val spark = SparkSession
        .builder()
        .appName("spark app")
        .getOrCreate()

**Comment by mikela** [comment]
no idea then, sorry
